# Generated by Django 4.2 on 2023-04-16 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('overview', models.TextField()),
                ('date', models.DateTimeField()),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=200)),
                ('status', models.PositiveSmallIntegerField()),
                ('group_name', models.CharField(max_length=254)),
                ('street', models.CharField(max_length=254)),
                ('city', models.CharField(max_length=254)),
                ('zipcode', models.CharField(max_length=254)),
                ('band_director_name', models.CharField(max_length=254)),
                ('band_director_phone', models.CharField(max_length=254)),
                ('band_director_email', models.CharField(max_length=254)),
                ('booster_parent_name', models.CharField(max_length=254)),
                ('booster_parent_phone', models.CharField(max_length=254)),
                ('booster_parent_email', models.CharField(max_length=254)),
                ('parade_march_title', models.CharField(max_length=254)),
                ('parade_march_composer', models.CharField(max_length=254)),
                ('additional_band_staff_names', models.CharField(max_length=254)),
                ('drum_major', models.CharField(max_length=254)),
                ('drum_major_name', models.CharField(max_length=254)),
                ('color_guard_advisor', models.CharField(max_length=254)),
                ('color_guard_captains', models.CharField(max_length=254)),
                ('drill_team', models.CharField(max_length=254)),
                ('drill_team_advisor', models.CharField(max_length=254)),
                ('drill_team_captains', models.CharField(max_length=254)),
                ('school_enrollment', models.CharField(max_length=254)),
                ('number_of_students_in_band', models.PositiveSmallIntegerField()),
                ('number_of_students_in_color_guard', models.PositiveSmallIntegerField()),
                ('number_of_students_in_drill_team', models.PositiveSmallIntegerField()),
                ('number_of_buses', models.PositiveSmallIntegerField()),
                ('number_of_box_trucks', models.PositiveSmallIntegerField()),
                ('number_of_trailers', models.PositiveSmallIntegerField()),
                ('number_of_tractor_trailer_rigs', models.PositiveSmallIntegerField()),
                ('special_instructions', models.CharField(max_length=254)),
                ('event', models.ManyToManyField(related_name='events', to='events.event')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
