version: "3.8"

services:
    backend:
        build: ./backend
        depends_on:
            - db
        volumes:
            - ./backend:/usr/src/app
        ports:
            - 8000:8000
        expose:
            - 8000

    frontend:
        image: node:alpine
        container_name: frontend
        entrypoint: /bin/sh
        ports:
            - 3000:3000
        working_dir: /srv/app
        volumes:
            - type: bind
              source: ./
              target: /srv/app
        tty: true

    reverse_proxy:
        build: ./nginx
        ports:
            - 80:80
        depends_on:
            - backend
            - frontend

    db:
        container_name: backend_db
        image: postgres:12.0-alpine
        restart: always
        # env_file: .env
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=Coll@b#2023

volumes:
    static_volume:
    postgres_data:
