version: "3.8"

services:
    backend:
        build: ./backend
        volumes:
            - ./backend:/usr/src/app
        expose:
            - 8000

    frontend:
        image: node:alpine
        container_name: frontend
        entrypoint: /bin/sh
        ports:
            - 3000:3000
        working_dir: /srv/app
        volumes:
            - type: bind
              source: ./
              target: /srv/app
        tty: true

    reverse_proxy:
        build: ./nginx
        ports:
            - 81:80
        depends_on:
            - backend
            - frontend
